language: node_js

node_js:
  - "9"

branches:
  only:
  - master

scripts:
  - yarn install codecov -g
  - yarn test

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - codecov

cache:
  yarn: true